name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  TF_VAR_aws_region: us-east-1 # Replace with your desired AWS region

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 # Replace with your desired Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform # Replace with your Terraform code directory

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: ./terraform 

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform 

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.tfplan
        working-directory: ./terraform 

      - name: Upload Plan as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./terraform/plan.tfplan

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only apply on push to main
        run: terraform apply -auto-approve plan.tfplan
        working-directory: ./terraform
